// Mocks generated by Mockito 5.4.5 from annotations
// in reaxit/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:reaxit/api/api_repository.dart' as _i6;
import 'package:reaxit/blocs/auth_cubit.dart' as _i2;
import 'package:reaxit/blocs/payment_user_cubit.dart' as _i7;
import 'package:reaxit/blocs/welcome_cubit.dart' as _i8;
import 'package:reaxit/config.dart' as _i3;
import 'package:reaxit/models.dart' as _i4;
import 'package:reaxit/models/announcement.dart' as _i12;
import 'package:reaxit/models/thabloid.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfig_1 extends _i1.SmartFake implements _i3.Config {
  _FakeConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvent_2 extends _i1.SmartFake implements _i4.Event {
  _FakeEvent_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListResponse_3<T> extends _i1.SmartFake
    implements _i4.ListResponse<T> {
  _FakeListResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventRegistration_4 extends _i1.SmartFake
    implements _i4.EventRegistration {
  _FakeEventRegistration_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminEvent_5 extends _i1.SmartFake implements _i4.AdminEvent {
  _FakeAdminEvent_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminEventRegistration_6 extends _i1.SmartFake
    implements _i4.AdminEventRegistration {
  _FakeAdminEventRegistration_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayable_7 extends _i1.SmartFake implements _i4.Payable {
  _FakePayable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodEvent_8 extends _i1.SmartFake implements _i4.FoodEvent {
  _FakeFoodEvent_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodOrder_9 extends _i1.SmartFake implements _i4.FoodOrder {
  _FakeFoodOrder_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentUser_10 extends _i1.SmartFake implements _i4.PaymentUser {
  _FakePaymentUser_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMember_11 extends _i1.SmartFake implements _i4.Member {
  _FakeMember_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFullMember_12 extends _i1.SmartFake implements _i4.FullMember {
  _FakeFullMember_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlbum_13 extends _i1.SmartFake implements _i4.Album {
  _FakeAlbum_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThabloid_14 extends _i1.SmartFake implements _i5.Thabloid {
  _FakeThabloid_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDevice_15 extends _i1.SmartFake implements _i4.Device {
  _FakeDevice_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSalesOrder_16 extends _i1.SmartFake implements _i4.SalesOrder {
  _FakeSalesOrder_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGroup_17 extends _i1.SmartFake implements _i4.Group {
  _FakeGroup_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiRepository_18 extends _i1.SmartFake implements _i6.ApiRepository {
  _FakeApiRepository_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentUserState_19 extends _i1.SmartFake
    implements _i7.PaymentUserState {
  _FakePaymentUserState_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWelcomeState_20 extends _i1.SmartFake implements _i8.WelcomeState {
  _FakeWelcomeState_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCubit extends _i1.Mock implements _i2.AuthCubit {
  MockAuthCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_0(this, Invocation.getter(#state)),
          )
          as _i2.AuthState);

  @override
  _i9.Stream<_i2.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i2.AuthState>.empty(),
          )
          as _i9.Stream<_i2.AuthState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i9.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logIn(_i2.Environment? environment) =>
      (super.noSuchMethod(
            Invocation.method(#logIn, [environment]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logOut() =>
      (super.noSuchMethod(
            Invocation.method(#logOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void selectEnvironment(_i2.Environment? environment) => super.noSuchMethod(
    Invocation.method(#selectEnvironment, [environment]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i2.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [ApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRepository extends _i1.Mock implements _i6.ApiRepository {
  MockApiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Config get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeConfig_1(this, Invocation.getter(#config)),
          )
          as _i3.Config);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<_i4.Event> getEventByPk({required int? pk}) =>
      (super.noSuchMethod(
            Invocation.method(#getEventByPk, [], {#pk: pk}),
            returnValue: _i9.Future<_i4.Event>.value(
              _FakeEvent_2(
                this,
                Invocation.method(#getEventByPk, [], {#pk: pk}),
              ),
            ),
          )
          as _i9.Future<_i4.Event>);

  @override
  _i9.Future<_i4.Event> getEventBySlug({required String? slug}) =>
      (super.noSuchMethod(
            Invocation.method(#getEventBySlug, [], {#slug: slug}),
            returnValue: _i9.Future<_i4.Event>.value(
              _FakeEvent_2(
                this,
                Invocation.method(#getEventBySlug, [], {#slug: slug}),
              ),
            ),
          )
          as _i9.Future<_i4.Event>);

  @override
  _i9.Future<_i4.ListResponse<_i4.Event>> getEvents({
    String? search,
    int? limit,
    int? offset,
    String? ordering,
    DateTime? start,
    DateTime? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [], {
              #search: search,
              #limit: limit,
              #offset: offset,
              #ordering: ordering,
              #start: start,
              #end: end,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i4.Event>>.value(
              _FakeListResponse_3<_i4.Event>(
                this,
                Invocation.method(#getEvents, [], {
                  #search: search,
                  #limit: limit,
                  #offset: offset,
                  #ordering: ordering,
                  #start: start,
                  #end: end,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.Event>>);

  @override
  _i9.Future<_i4.ListResponse<_i4.PartnerEvent>> getPartnerEvents({
    String? search,
    int? limit,
    int? offset,
    String? ordering,
    DateTime? start,
    DateTime? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPartnerEvents, [], {
              #search: search,
              #limit: limit,
              #offset: offset,
              #ordering: ordering,
              #start: start,
              #end: end,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i4.PartnerEvent>>.value(
              _FakeListResponse_3<_i4.PartnerEvent>(
                this,
                Invocation.method(#getPartnerEvents, [], {
                  #search: search,
                  #limit: limit,
                  #offset: offset,
                  #ordering: ordering,
                  #start: start,
                  #end: end,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.PartnerEvent>>);

  @override
  _i9.Future<_i4.ListResponse<_i4.EventRegistration>> getEventRegistrations({
    required int? pk,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEventRegistrations, [], {
              #pk: pk,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i9.Future<_i4.ListResponse<_i4.EventRegistration>>.value(
                  _FakeListResponse_3<_i4.EventRegistration>(
                    this,
                    Invocation.method(#getEventRegistrations, [], {
                      #pk: pk,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i4.ListResponse<_i4.EventRegistration>>);

  @override
  _i9.Future<_i4.EventRegistration> registerForEvent(int? pk) =>
      (super.noSuchMethod(
            Invocation.method(#registerForEvent, [pk]),
            returnValue: _i9.Future<_i4.EventRegistration>.value(
              _FakeEventRegistration_4(
                this,
                Invocation.method(#registerForEvent, [pk]),
              ),
            ),
          )
          as _i9.Future<_i4.EventRegistration>);

  @override
  _i9.Future<void> cancelRegistration({
    required int? eventPk,
    required int? registrationPk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelRegistration, [], {
              #eventPk: eventPk,
              #registrationPk: registrationPk,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<Map<String, _i4.RegistrationField>> getRegistrationFields({
    required int? eventPk,
    required int? registrationPk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRegistrationFields, [], {
              #eventPk: eventPk,
              #registrationPk: registrationPk,
            }),
            returnValue: _i9.Future<Map<String, _i4.RegistrationField>>.value(
              <String, _i4.RegistrationField>{},
            ),
          )
          as _i9.Future<Map<String, _i4.RegistrationField>>);

  @override
  _i9.Future<void> updateRegistrationFields({
    required int? eventPk,
    required int? registrationPk,
    required Map<String, _i4.RegistrationField>? fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRegistrationFields, [], {
              #eventPk: eventPk,
              #registrationPk: registrationPk,
              #fields: fields,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.AdminEvent> getAdminEvent({required int? pk}) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminEvent, [], {#pk: pk}),
            returnValue: _i9.Future<_i4.AdminEvent>.value(
              _FakeAdminEvent_5(
                this,
                Invocation.method(#getAdminEvent, [], {#pk: pk}),
              ),
            ),
          )
          as _i9.Future<_i4.AdminEvent>);

  @override
  _i9.Future<_i4.ListResponse<_i4.AdminEventRegistration>>
  getAdminEventRegistrations({
    required int? pk,
    int? limit,
    int? offset,
    String? search,
    String? ordering,
    bool? cancelled,
    bool? queued,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminEventRegistrations, [], {
              #pk: pk,
              #limit: limit,
              #offset: offset,
              #search: search,
              #ordering: ordering,
              #cancelled: cancelled,
              #queued: queued,
            }),
            returnValue:
                _i9.Future<_i4.ListResponse<_i4.AdminEventRegistration>>.value(
                  _FakeListResponse_3<_i4.AdminEventRegistration>(
                    this,
                    Invocation.method(#getAdminEventRegistrations, [], {
                      #pk: pk,
                      #limit: limit,
                      #offset: offset,
                      #search: search,
                      #ordering: ordering,
                      #cancelled: cancelled,
                      #queued: queued,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i4.ListResponse<_i4.AdminEventRegistration>>);

  @override
  _i9.Future<String> markPresentEventRegistration({
    required int? eventPk,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markPresentEventRegistration, [], {
              #eventPk: eventPk,
              #token: token,
            }),
            returnValue: _i9.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#markPresentEventRegistration, [], {
                  #eventPk: eventPk,
                  #token: token,
                }),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<_i4.AdminEventRegistration> markPresentAdminEventRegistration({
    required int? eventPk,
    required int? registrationPk,
    required bool? present,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markPresentAdminEventRegistration, [], {
              #eventPk: eventPk,
              #registrationPk: registrationPk,
              #present: present,
            }),
            returnValue: _i9.Future<_i4.AdminEventRegistration>.value(
              _FakeAdminEventRegistration_6(
                this,
                Invocation.method(#markPresentAdminEventRegistration, [], {
                  #eventPk: eventPk,
                  #registrationPk: registrationPk,
                  #present: present,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.AdminEventRegistration>);

  @override
  _i9.Future<_i4.Payable> markPaidAdminEventRegistration({
    required int? registrationPk,
    required _i4.PaymentType? paymentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markPaidAdminEventRegistration, [], {
              #registrationPk: registrationPk,
              #paymentType: paymentType,
            }),
            returnValue: _i9.Future<_i4.Payable>.value(
              _FakePayable_7(
                this,
                Invocation.method(#markPaidAdminEventRegistration, [], {
                  #registrationPk: registrationPk,
                  #paymentType: paymentType,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Payable>);

  @override
  _i9.Future<void> markNotPaidAdminEventRegistration({
    required int? registrationPk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markNotPaidAdminEventRegistration, [], {
              #registrationPk: registrationPk,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.ListResponse<_i4.AdminFoodOrder>> getAdminFoodOrders({
    required int? pk,
    int? limit,
    int? offset,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminFoodOrders, [], {
              #pk: pk,
              #limit: limit,
              #offset: offset,
              #search: search,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i4.AdminFoodOrder>>.value(
              _FakeListResponse_3<_i4.AdminFoodOrder>(
                this,
                Invocation.method(#getAdminFoodOrders, [], {
                  #pk: pk,
                  #limit: limit,
                  #offset: offset,
                  #search: search,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.AdminFoodOrder>>);

  @override
  _i9.Future<_i4.Payable> markPaidAdminFoodOrder({
    required int? orderPk,
    required _i4.PaymentType? paymentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markPaidAdminFoodOrder, [], {
              #orderPk: orderPk,
              #paymentType: paymentType,
            }),
            returnValue: _i9.Future<_i4.Payable>.value(
              _FakePayable_7(
                this,
                Invocation.method(#markPaidAdminFoodOrder, [], {
                  #orderPk: orderPk,
                  #paymentType: paymentType,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Payable>);

  @override
  _i9.Future<void> markNotPaidAdminFoodOrder({required int? orderPk}) =>
      (super.noSuchMethod(
            Invocation.method(#markNotPaidAdminFoodOrder, [], {
              #orderPk: orderPk,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.FoodEvent> getFoodEvent(int? pk) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodEvent, [pk]),
            returnValue: _i9.Future<_i4.FoodEvent>.value(
              _FakeFoodEvent_8(this, Invocation.method(#getFoodEvent, [pk])),
            ),
          )
          as _i9.Future<_i4.FoodEvent>);

  @override
  _i9.Future<_i4.ListResponse<_i4.FoodEvent>> getFoodEvents({
    int? limit,
    int? offset,
    String? ordering,
    DateTime? start,
    DateTime? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodEvents, [], {
              #limit: limit,
              #offset: offset,
              #ordering: ordering,
              #start: start,
              #end: end,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i4.FoodEvent>>.value(
              _FakeListResponse_3<_i4.FoodEvent>(
                this,
                Invocation.method(#getFoodEvents, [], {
                  #limit: limit,
                  #offset: offset,
                  #ordering: ordering,
                  #start: start,
                  #end: end,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.FoodEvent>>);

  @override
  _i9.Future<_i4.FoodEvent> getCurrentFoodEvent() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentFoodEvent, []),
            returnValue: _i9.Future<_i4.FoodEvent>.value(
              _FakeFoodEvent_8(
                this,
                Invocation.method(#getCurrentFoodEvent, []),
              ),
            ),
          )
          as _i9.Future<_i4.FoodEvent>);

  @override
  _i9.Future<_i4.FoodOrder> getFoodOrder(int? pk) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodOrder, [pk]),
            returnValue: _i9.Future<_i4.FoodOrder>.value(
              _FakeFoodOrder_9(this, Invocation.method(#getFoodOrder, [pk])),
            ),
          )
          as _i9.Future<_i4.FoodOrder>);

  @override
  _i9.Future<void> cancelFoodOrder(int? pk) =>
      (super.noSuchMethod(
            Invocation.method(#cancelFoodOrder, [pk]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.FoodOrder> placeFoodOrder({
    required int? eventPk,
    required int? productPk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#placeFoodOrder, [], {
              #eventPk: eventPk,
              #productPk: productPk,
            }),
            returnValue: _i9.Future<_i4.FoodOrder>.value(
              _FakeFoodOrder_9(
                this,
                Invocation.method(#placeFoodOrder, [], {
                  #eventPk: eventPk,
                  #productPk: productPk,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.FoodOrder>);

  @override
  _i9.Future<_i4.FoodOrder> changeFoodOrder({
    required int? eventPk,
    required int? productPk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeFoodOrder, [], {
              #eventPk: eventPk,
              #productPk: productPk,
            }),
            returnValue: _i9.Future<_i4.FoodOrder>.value(
              _FakeFoodOrder_9(
                this,
                Invocation.method(#changeFoodOrder, [], {
                  #eventPk: eventPk,
                  #productPk: productPk,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.FoodOrder>);

  @override
  _i9.Future<_i4.ListResponse<_i4.Product>> getFoodEventProducts(
    int? pk, {
    int? limit,
    int? offset,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFoodEventProducts,
              [pk],
              {#limit: limit, #offset: offset, #search: search},
            ),
            returnValue: _i9.Future<_i4.ListResponse<_i4.Product>>.value(
              _FakeListResponse_3<_i4.Product>(
                this,
                Invocation.method(
                  #getFoodEventProducts,
                  [pk],
                  {#limit: limit, #offset: offset, #search: search},
                ),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.Product>>);

  @override
  _i9.Future<_i4.PaymentUser> getPaymentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentUser, []),
            returnValue: _i9.Future<_i4.PaymentUser>.value(
              _FakePaymentUser_10(this, Invocation.method(#getPaymentUser, [])),
            ),
          )
          as _i9.Future<_i4.PaymentUser>);

  @override
  _i9.Future<_i4.Payable> getFoodOrderPayable({required int? foodOrderPk}) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodOrderPayable, [], {
              #foodOrderPk: foodOrderPk,
            }),
            returnValue: _i9.Future<_i4.Payable>.value(
              _FakePayable_7(
                this,
                Invocation.method(#getFoodOrderPayable, [], {
                  #foodOrderPk: foodOrderPk,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Payable>);

  @override
  _i9.Future<_i4.Payable> thaliaPayFoodOrder({required int? foodOrderPk}) =>
      (super.noSuchMethod(
            Invocation.method(#thaliaPayFoodOrder, [], {
              #foodOrderPk: foodOrderPk,
            }),
            returnValue: _i9.Future<_i4.Payable>.value(
              _FakePayable_7(
                this,
                Invocation.method(#thaliaPayFoodOrder, [], {
                  #foodOrderPk: foodOrderPk,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Payable>);

  @override
  _i9.Future<_i4.Payable> getEventRegistrationPayable({
    required int? registrationPk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEventRegistrationPayable, [], {
              #registrationPk: registrationPk,
            }),
            returnValue: _i9.Future<_i4.Payable>.value(
              _FakePayable_7(
                this,
                Invocation.method(#getEventRegistrationPayable, [], {
                  #registrationPk: registrationPk,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Payable>);

  @override
  _i9.Future<_i4.Payable> thaliaPayRegistration({
    required int? registrationPk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#thaliaPayRegistration, [], {
              #registrationPk: registrationPk,
            }),
            returnValue: _i9.Future<_i4.Payable>.value(
              _FakePayable_7(
                this,
                Invocation.method(#thaliaPayRegistration, [], {
                  #registrationPk: registrationPk,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Payable>);

  @override
  _i9.Future<_i4.Payable> getSalesOrderPayable({
    required String? salesOrderPk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSalesOrderPayable, [], {
              #salesOrderPk: salesOrderPk,
            }),
            returnValue: _i9.Future<_i4.Payable>.value(
              _FakePayable_7(
                this,
                Invocation.method(#getSalesOrderPayable, [], {
                  #salesOrderPk: salesOrderPk,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Payable>);

  @override
  _i9.Future<_i4.Payable> thaliaPaySalesOrder({
    required String? salesOrderPk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#thaliaPaySalesOrder, [], {
              #salesOrderPk: salesOrderPk,
            }),
            returnValue: _i9.Future<_i4.Payable>.value(
              _FakePayable_7(
                this,
                Invocation.method(#thaliaPaySalesOrder, [], {
                  #salesOrderPk: salesOrderPk,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Payable>);

  @override
  _i9.Future<_i4.Member> getMember({required int? pk}) =>
      (super.noSuchMethod(
            Invocation.method(#getMember, [], {#pk: pk}),
            returnValue: _i9.Future<_i4.Member>.value(
              _FakeMember_11(
                this,
                Invocation.method(#getMember, [], {#pk: pk}),
              ),
            ),
          )
          as _i9.Future<_i4.Member>);

  @override
  _i9.Future<_i4.ListResponse<_i4.ListMember>> getMembers({
    String? search,
    int? limit,
    int? offset,
    String? ordering,
    int? year,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, [], {
              #search: search,
              #limit: limit,
              #offset: offset,
              #ordering: ordering,
              #year: year,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i4.ListMember>>.value(
              _FakeListResponse_3<_i4.ListMember>(
                this,
                Invocation.method(#getMembers, [], {
                  #search: search,
                  #limit: limit,
                  #offset: offset,
                  #ordering: ordering,
                  #year: year,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.ListMember>>);

  @override
  _i9.Future<_i4.FullMember> getMe() =>
      (super.noSuchMethod(
            Invocation.method(#getMe, []),
            returnValue: _i9.Future<_i4.FullMember>.value(
              _FakeFullMember_12(this, Invocation.method(#getMe, [])),
            ),
          )
          as _i9.Future<_i4.FullMember>);

  @override
  _i9.Future<void> updateAvatar(String? file) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvatar, [file]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateDescription(String? description) =>
      (super.noSuchMethod(
            Invocation.method(#updateDescription, [description]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.Album> getAlbum({required String? slug}) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbum, [], {#slug: slug}),
            returnValue: _i9.Future<_i4.Album>.value(
              _FakeAlbum_13(
                this,
                Invocation.method(#getAlbum, [], {#slug: slug}),
              ),
            ),
          )
          as _i9.Future<_i4.Album>);

  @override
  _i9.Future<void> updateLiked(int? id, bool? liked) =>
      (super.noSuchMethod(
            Invocation.method(#updateLiked, [id, liked]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.ListResponse<_i4.ListAlbum>> getAlbums({
    String? search,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbums, [], {
              #search: search,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i4.ListAlbum>>.value(
              _FakeListResponse_3<_i4.ListAlbum>(
                this,
                Invocation.method(#getAlbums, [], {
                  #search: search,
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.ListAlbum>>);

  @override
  _i9.Future<_i4.ListResponse<_i5.Thabloid>> getThabloids({
    String? search,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getThabloids, [], {
              #search: search,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i5.Thabloid>>.value(
              _FakeListResponse_3<_i5.Thabloid>(
                this,
                Invocation.method(#getThabloids, [], {
                  #search: search,
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i5.Thabloid>>);

  @override
  _i9.Future<_i5.Thabloid> getThabloid({required int? pk}) =>
      (super.noSuchMethod(
            Invocation.method(#getThabloid, [], {#pk: pk}),
            returnValue: _i9.Future<_i5.Thabloid>.value(
              _FakeThabloid_14(
                this,
                Invocation.method(#getThabloid, [], {#pk: pk}),
              ),
            ),
          )
          as _i9.Future<_i5.Thabloid>);

  @override
  _i9.Future<_i4.ListResponse<_i4.Slide>> getSlides({
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSlides, [], {#limit: limit, #offset: offset}),
            returnValue: _i9.Future<_i4.ListResponse<_i4.Slide>>.value(
              _FakeListResponse_3<_i4.Slide>(
                this,
                Invocation.method(#getSlides, [], {
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.Slide>>);

  @override
  _i9.Future<List<_i12.Announcement>> getAnnouncements() =>
      (super.noSuchMethod(
            Invocation.method(#getAnnouncements, []),
            returnValue: _i9.Future<List<_i12.Announcement>>.value(
              <_i12.Announcement>[],
            ),
          )
          as _i9.Future<List<_i12.Announcement>>);

  @override
  _i9.Future<_i4.ListResponse<_i4.FrontpageArticle>> getFrontpageArticles({
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFrontpageArticles, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i9.Future<_i4.ListResponse<_i4.FrontpageArticle>>.value(
                  _FakeListResponse_3<_i4.FrontpageArticle>(
                    this,
                    Invocation.method(#getFrontpageArticles, [], {
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i4.ListResponse<_i4.FrontpageArticle>>);

  @override
  _i9.Future<_i4.Device> registerDevice({
    required String? token,
    required String? type,
    bool? active = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerDevice, [], {
              #token: token,
              #type: type,
              #active: active,
            }),
            returnValue: _i9.Future<_i4.Device>.value(
              _FakeDevice_15(
                this,
                Invocation.method(#registerDevice, [], {
                  #token: token,
                  #type: type,
                  #active: active,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Device>);

  @override
  _i9.Future<_i4.Device> getDevice({required int? pk}) =>
      (super.noSuchMethod(
            Invocation.method(#getDevice, [], {#pk: pk}),
            returnValue: _i9.Future<_i4.Device>.value(
              _FakeDevice_15(
                this,
                Invocation.method(#getDevice, [], {#pk: pk}),
              ),
            ),
          )
          as _i9.Future<_i4.Device>);

  @override
  _i9.Future<_i4.Device> disableDevice({required int? pk}) =>
      (super.noSuchMethod(
            Invocation.method(#disableDevice, [], {#pk: pk}),
            returnValue: _i9.Future<_i4.Device>.value(
              _FakeDevice_15(
                this,
                Invocation.method(#disableDevice, [], {#pk: pk}),
              ),
            ),
          )
          as _i9.Future<_i4.Device>);

  @override
  _i9.Future<_i4.Device> updateDeviceToken({
    required int? pk,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeviceToken, [], {#pk: pk, #token: token}),
            returnValue: _i9.Future<_i4.Device>.value(
              _FakeDevice_15(
                this,
                Invocation.method(#updateDeviceToken, [], {
                  #pk: pk,
                  #token: token,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Device>);

  @override
  _i9.Future<_i4.Device> updateDeviceReceiveCategory({
    required int? pk,
    required List<String>? receiveCategory,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeviceReceiveCategory, [], {
              #pk: pk,
              #receiveCategory: receiveCategory,
            }),
            returnValue: _i9.Future<_i4.Device>.value(
              _FakeDevice_15(
                this,
                Invocation.method(#updateDeviceReceiveCategory, [], {
                  #pk: pk,
                  #receiveCategory: receiveCategory,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Device>);

  @override
  _i9.Future<_i4.ListResponse<_i4.PushNotificationCategory>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i9.Future<
              _i4.ListResponse<_i4.PushNotificationCategory>
            >.value(
              _FakeListResponse_3<_i4.PushNotificationCategory>(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.PushNotificationCategory>>);

  @override
  _i9.Future<_i4.SalesOrder> claimSalesOrder({required String? pk}) =>
      (super.noSuchMethod(
            Invocation.method(#claimSalesOrder, [], {#pk: pk}),
            returnValue: _i9.Future<_i4.SalesOrder>.value(
              _FakeSalesOrder_16(
                this,
                Invocation.method(#claimSalesOrder, [], {#pk: pk}),
              ),
            ),
          )
          as _i9.Future<_i4.SalesOrder>);

  @override
  _i9.Future<_i4.ListResponse<_i4.ListGroup>> getGroups({
    int? limit,
    int? offset,
    _i4.MemberGroupType? type,
    DateTime? start,
    DateTime? end,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGroups, [], {
              #limit: limit,
              #offset: offset,
              #type: type,
              #start: start,
              #end: end,
              #search: search,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i4.ListGroup>>.value(
              _FakeListResponse_3<_i4.ListGroup>(
                this,
                Invocation.method(#getGroups, [], {
                  #limit: limit,
                  #offset: offset,
                  #type: type,
                  #start: start,
                  #end: end,
                  #search: search,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.ListGroup>>);

  @override
  _i9.Future<_i4.Group> getGroup({required int? pk}) =>
      (super.noSuchMethod(
            Invocation.method(#getGroup, [], {#pk: pk}),
            returnValue: _i9.Future<_i4.Group>.value(
              _FakeGroup_17(this, Invocation.method(#getGroup, [], {#pk: pk})),
            ),
          )
          as _i9.Future<_i4.Group>);

  @override
  _i9.Future<_i4.Group> getGroupBySlug({
    required _i4.MemberGroupType? type,
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupBySlug, [], {#type: type, #slug: slug}),
            returnValue: _i9.Future<_i4.Group>.value(
              _FakeGroup_17(
                this,
                Invocation.method(#getGroupBySlug, [], {
                  #type: type,
                  #slug: slug,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.Group>);

  @override
  _i9.Future<_i4.ListResponse<_i4.AlbumPhoto>> getLikedPhotos({
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLikedPhotos, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i4.AlbumPhoto>>.value(
              _FakeListResponse_3<_i4.AlbumPhoto>(
                this,
                Invocation.method(#getLikedPhotos, [], {
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.AlbumPhoto>>);

  @override
  _i9.Future<_i4.ListResponse<_i4.Payment>> getPayments({
    int? limit,
    int? offset,
    String? ordering,
    DateTime? start,
    DateTime? end,
    List<_i4.PaymentType>? type,
    bool? settled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPayments, [], {
              #limit: limit,
              #offset: offset,
              #ordering: ordering,
              #start: start,
              #end: end,
              #type: type,
              #settled: settled,
            }),
            returnValue: _i9.Future<_i4.ListResponse<_i4.Payment>>.value(
              _FakeListResponse_3<_i4.Payment>(
                this,
                Invocation.method(#getPayments, [], {
                  #limit: limit,
                  #offset: offset,
                  #ordering: ordering,
                  #start: start,
                  #end: end,
                  #type: type,
                  #settled: settled,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.ListResponse<_i4.Payment>>);
}

/// A class which mocks [PaymentUserCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentUserCubit extends _i1.Mock implements _i7.PaymentUserCubit {
  MockPaymentUserCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ApiRepository get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeApiRepository_18(this, Invocation.getter(#api)),
          )
          as _i6.ApiRepository);

  @override
  _i7.PaymentUserState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePaymentUserState_19(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.PaymentUserState);

  @override
  _i9.Stream<_i7.PaymentUserState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i7.PaymentUserState>.empty(),
          )
          as _i9.Stream<_i7.PaymentUserState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i9.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void emit(_i7.PaymentUserState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i7.PaymentUserState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [WelcomeCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWelcomeCubit extends _i1.Mock implements _i8.WelcomeCubit {
  MockWelcomeCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ApiRepository get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeApiRepository_18(this, Invocation.getter(#api)),
          )
          as _i6.ApiRepository);

  @override
  _i8.WelcomeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeWelcomeState_20(this, Invocation.getter(#state)),
          )
          as _i8.WelcomeState);

  @override
  _i9.Stream<_i8.WelcomeState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i8.WelcomeState>.empty(),
          )
          as _i9.Stream<_i8.WelcomeState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i9.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void emit(_i8.WelcomeState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i8.WelcomeState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
