// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJMgr3wSpkB8Kf4N1-ibi7MUctxoDrDyI',
    appId: '1:488731759938:android:ce90d9e7effcbbfb',
    messagingSenderId: '488731759938',
    projectId: 'thalia-493a0',
    databaseURL: 'https://thalia-493a0.firebaseio.com',
    storageBucket: 'thalia-493a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTFj7iwysI-luA9aP_XFLsQh2CQP-gxqc',
    appId: '1:488731759938:ios:ce90d9e7effcbbfb',
    messagingSenderId: '488731759938',
    projectId: 'thalia-493a0',
    databaseURL: 'https://thalia-493a0.firebaseio.com',
    storageBucket: 'thalia-493a0.appspot.com',
    androidClientId: '488731759938-doctddnhajp9teh4t1dktdcd18he6g6k.apps.googleusercontent.com',
    iosClientId: '488731759938-vkauvr25l1n4te0urfe721pi60hetttu.apps.googleusercontent.com',
    iosBundleId: 'com.thaliapp',
  );
}
