if not is_ci?
  update_fastlane
end
skip_docs

default_platform(:ios)

platform :ios do
  private_lane :setup_project do |options|
    if is_ci?
      xcversion(version: "~> 12.0")
      create_keychain(
        name: "fastlane-keychain",
        password: ENV["KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
    end
    sh("yarn install --frozen-lockfile")
    cocoapods
    match(
      type: options[:type],
      readonly: is_ci,
      keychain_name: is_ci? ? "fastlane-keychain" : nil,
      keychain_password: is_ci? ? ENV["KEYCHAIN_PASSWORD"] : nil
    )
  end

  desc "Runs a build"
  lane :build do
    setup_project
    build_app(
      workspace: "ThaliApp.xcworkspace",
      scheme: "ThaliApp",
      skip_archive: true,
      skip_package_ipa: true
    )
  end

  desc "Execute Adhoc build"
  lane :deploy_adhoc do
    setup_project(type: "adhoc")
    update_project_provisioning(
      xcodeproj: "ThaliApp.xcodeproj",
      profile: ENV["sigh_com.thaliapp_adhoc_profile-path"],
      build_configuration: "Release"
    )
    build_app(
      workspace: "ThaliApp.xcworkspace",
      scheme: "ThaliApp",
      export_method: "ad-hoc"
    )
  end

  desc "Push a new internal build to TestFlight"
  lane :deploy_internal do
    setup_project(type: "appstore")
    increment_build_number({
      xcodeproj: "ThaliApp.xcodeproj",
      build_number: latest_testflight_build_number + 1
    })
    build_app(workspace: "ThaliApp.xcworkspace", scheme: "ThaliApp")
    upload_to_testflight
  end

  desc "Push a new beta build to TestFlight"
  lane :deploy_beta do
    setup_project(type: "appstore")
    increment_build_number({
      xcodeproj: "ThaliApp.xcodeproj",
      build_number: latest_testflight_build_number + 1
    })
    build_app(workspace: "ThaliApp.xcworkspace", scheme: "ThaliApp")
    upload_to_testflight(distribute_external: true)
  end

  desc "Push a new build to the App Store"
  lane :deploy_production do
    setup_project(type: "appstore")
    increment_build_number({
      xcodeproj: "ThaliApp.xcodeproj",
      build_number: app_store_build_number + 1
    })
    build_app(workspace: "ThaliApp.xcworkspace", scheme: "ThaliApp")
    upload_to_app_store(
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      automatic_release: true
    )
  end
end
