// Mocks generated by Mockito 5.0.17 from annotations
// in reaxit/test/mocks/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i13;
import 'dart:io' as _i17;

import 'package:mockito/mockito.dart' as _i1;
import 'package:reaxit/api/api_repository.dart' as _i12;
import 'package:reaxit/models/album.dart' as _i10;
import 'package:reaxit/models/device.dart' as _i11;
import 'package:reaxit/models/event.dart' as _i2;
import 'package:reaxit/models/event_registration.dart' as _i4;
import 'package:reaxit/models/food_event.dart' as _i6;
import 'package:reaxit/models/food_order.dart' as _i7;
import 'package:reaxit/models/frontpage_article.dart' as _i19;
import 'package:reaxit/models/list_response.dart' as _i3;
import 'package:reaxit/models/member.dart' as _i9;
import 'package:reaxit/models/payable.dart' as _i5;
import 'package:reaxit/models/payment.dart' as _i15;
import 'package:reaxit/models/payment_user.dart' as _i8;
import 'package:reaxit/models/product.dart' as _i16;
import 'package:reaxit/models/push_notification_category.dart' as _i20;
import 'package:reaxit/models/registration_field.dart' as _i14;
import 'package:reaxit/models/slide.dart' as _i18;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEvent_0 extends _i1.Fake implements _i2.Event {}

class _FakeListResponse_1<T> extends _i1.Fake implements _i3.ListResponse<T> {}

class _FakeEventRegistration_2 extends _i1.Fake
    implements _i4.EventRegistration {}

class _FakeAdminEventRegistration_3 extends _i1.Fake
    implements _i4.AdminEventRegistration {}

class _FakePayable_4 extends _i1.Fake implements _i5.Payable {}

class _FakeFoodEvent_5 extends _i1.Fake implements _i6.FoodEvent {}

class _FakeFoodOrder_6 extends _i1.Fake implements _i7.FoodOrder {}

class _FakePaymentUser_7 extends _i1.Fake implements _i8.PaymentUser {}

class _FakeMember_8 extends _i1.Fake implements _i9.Member {}

class _FakeFullMember_9 extends _i1.Fake implements _i9.FullMember {}

class _FakeAlbum_10 extends _i1.Fake implements _i10.Album {}

class _FakeDevice_11 extends _i1.Fake implements _i11.Device {}

/// A class which mocks [ApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRepository extends _i1.Mock implements _i12.ApiRepository {
  MockApiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  _i13.Future<_i2.Event> getEvent({int? pk}) =>
      (super.noSuchMethod(Invocation.method(#getEvent, [], {#pk: pk}),
              returnValue: Future<_i2.Event>.value(_FakeEvent_0()))
          as _i13.Future<_i2.Event>);
  @override
  _i13.Future<_i3.ListResponse<_i2.Event>> getEvents(
          {String? search,
          int? limit,
          int? offset,
          String? ordering,
          DateTime? start,
          DateTime? end}) =>
      (super.noSuchMethod(
              Invocation.method(#getEvents, [], {
                #search: search,
                #limit: limit,
                #offset: offset,
                #ordering: ordering,
                #start: start,
                #end: end
              }),
              returnValue: Future<_i3.ListResponse<_i2.Event>>.value(
                  _FakeListResponse_1<_i2.Event>()))
          as _i13.Future<_i3.ListResponse<_i2.Event>>);
  @override
  _i13.Future<_i3.ListResponse<_i2.PartnerEvent>> getPartnerEvents(
          {String? search,
          int? limit,
          int? offset,
          String? ordering,
          DateTime? start,
          DateTime? end}) =>
      (super.noSuchMethod(
              Invocation.method(#getPartnerEvents, [], {
                #search: search,
                #limit: limit,
                #offset: offset,
                #ordering: ordering,
                #start: start,
                #end: end
              }),
              returnValue: Future<_i3.ListResponse<_i2.PartnerEvent>>.value(
                  _FakeListResponse_1<_i2.PartnerEvent>()))
          as _i13.Future<_i3.ListResponse<_i2.PartnerEvent>>);
  @override
  _i13.Future<_i3.ListResponse<_i4.EventRegistration>> getEventRegistrations(
          {int? pk, int? limit, int? offset}) =>
      (super.noSuchMethod(
          Invocation.method(#getEventRegistrations, [],
              {#pk: pk, #limit: limit, #offset: offset}),
          returnValue: Future<_i3.ListResponse<_i4.EventRegistration>>.value(
              _FakeListResponse_1<_i4.EventRegistration>())) as _i13
          .Future<_i3.ListResponse<_i4.EventRegistration>>);
  @override
  _i13.Future<_i4.EventRegistration> registerForEvent(int? pk) =>
      (super.noSuchMethod(Invocation.method(#registerForEvent, [pk]),
              returnValue: Future<_i4.EventRegistration>.value(
                  _FakeEventRegistration_2()))
          as _i13.Future<_i4.EventRegistration>);
  @override
  _i13.Future<void> cancelRegistration({int? eventPk, int? registrationPk}) =>
      (super.noSuchMethod(
              Invocation.method(#cancelRegistration, [],
                  {#eventPk: eventPk, #registrationPk: registrationPk}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<Map<String, _i14.RegistrationField>> getRegistrationFields(
          {int? eventPk, int? registrationPk}) =>
      (super.noSuchMethod(
              Invocation.method(#getRegistrationFields, [],
                  {#eventPk: eventPk, #registrationPk: registrationPk}),
              returnValue: Future<Map<String, _i14.RegistrationField>>.value(
                  <String, _i14.RegistrationField>{}))
          as _i13.Future<Map<String, _i14.RegistrationField>>);
  @override
  _i13.Future<void> updateRegistrationFields(
          {int? eventPk,
          int? registrationPk,
          Map<String, _i14.RegistrationField>? fields}) =>
      (super.noSuchMethod(
              Invocation.method(#updateRegistrationFields, [], {
                #eventPk: eventPk,
                #registrationPk: registrationPk,
                #fields: fields
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<
      _i3.ListResponse<_i4.AdminEventRegistration>> getAdminEventRegistrations(
          {int? pk,
          int? limit,
          int? offset,
          String? search,
          String? ordering,
          bool? cancelled}) =>
      (super.noSuchMethod(
              Invocation.method(#getAdminEventRegistrations, [], {
                #pk: pk,
                #limit: limit,
                #offset: offset,
                #search: search,
                #ordering: ordering,
                #cancelled: cancelled
              }),
              returnValue:
                  Future<_i3.ListResponse<_i4.AdminEventRegistration>>.value(
                      _FakeListResponse_1<_i4.AdminEventRegistration>()))
          as _i13.Future<_i3.ListResponse<_i4.AdminEventRegistration>>);
  @override
  _i13.Future<_i4.AdminEventRegistration> markPresentAdminEventRegistration(
          {int? eventPk, int? registrationPk, bool? present}) =>
      (super.noSuchMethod(
              Invocation.method(#markPresentAdminEventRegistration, [], {
                #eventPk: eventPk,
                #registrationPk: registrationPk,
                #present: present
              }),
              returnValue: Future<_i4.AdminEventRegistration>.value(
                  _FakeAdminEventRegistration_3()))
          as _i13.Future<_i4.AdminEventRegistration>);
  @override
  _i13.Future<_i5.Payable> markPaidAdminEventRegistration(
          {int? registrationPk, _i15.PaymentType? paymentType}) =>
      (super.noSuchMethod(
              Invocation.method(#markPaidAdminEventRegistration, [],
                  {#registrationPk: registrationPk, #paymentType: paymentType}),
              returnValue: Future<_i5.Payable>.value(_FakePayable_4()))
          as _i13.Future<_i5.Payable>);
  @override
  _i13.Future<void> markNotPaidAdminEventRegistration({int? registrationPk}) =>
      (super.noSuchMethod(
              Invocation.method(#markNotPaidAdminEventRegistration, [],
                  {#registrationPk: registrationPk}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<_i3.ListResponse<_i7.FoodOrder>> getAdminFoodOrders(
          {int? pk, int? limit, int? offset, String? search}) =>
      (super.noSuchMethod(
              Invocation.method(#getAdminFoodOrders, [],
                  {#pk: pk, #limit: limit, #offset: offset, #search: search}),
              returnValue: Future<_i3.ListResponse<_i7.FoodOrder>>.value(
                  _FakeListResponse_1<_i7.FoodOrder>()))
          as _i13.Future<_i3.ListResponse<_i7.FoodOrder>>);
  @override
  _i13.Future<_i5.Payable> markPaidAdminFoodOrder(
          {int? orderPk, _i15.PaymentType? paymentType}) =>
      (super.noSuchMethod(
              Invocation.method(#markPaidAdminFoodOrder, [],
                  {#orderPk: orderPk, #paymentType: paymentType}),
              returnValue: Future<_i5.Payable>.value(_FakePayable_4()))
          as _i13.Future<_i5.Payable>);
  @override
  _i13.Future<void> markNotPaidAdminFoodOrder({int? orderPk}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #markNotPaidAdminFoodOrder, [], {#orderPk: orderPk}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<_i6.FoodEvent> getFoodEvent(int? pk) =>
      (super.noSuchMethod(Invocation.method(#getFoodEvent, [pk]),
              returnValue: Future<_i6.FoodEvent>.value(_FakeFoodEvent_5()))
          as _i13.Future<_i6.FoodEvent>);
  @override
  _i13.Future<_i3.ListResponse<_i6.FoodEvent>> getFoodEvents(
          {int? limit,
          int? offset,
          String? ordering,
          DateTime? start,
          DateTime? end}) =>
      (super.noSuchMethod(
              Invocation.method(#getFoodEvents, [], {
                #limit: limit,
                #offset: offset,
                #ordering: ordering,
                #start: start,
                #end: end
              }),
              returnValue: Future<_i3.ListResponse<_i6.FoodEvent>>.value(
                  _FakeListResponse_1<_i6.FoodEvent>()))
          as _i13.Future<_i3.ListResponse<_i6.FoodEvent>>);
  @override
  _i13.Future<_i6.FoodEvent> getCurrentFoodEvent() =>
      (super.noSuchMethod(Invocation.method(#getCurrentFoodEvent, []),
              returnValue: Future<_i6.FoodEvent>.value(_FakeFoodEvent_5()))
          as _i13.Future<_i6.FoodEvent>);
  @override
  _i13.Future<_i7.FoodOrder> getFoodOrder(int? pk) =>
      (super.noSuchMethod(Invocation.method(#getFoodOrder, [pk]),
              returnValue: Future<_i7.FoodOrder>.value(_FakeFoodOrder_6()))
          as _i13.Future<_i7.FoodOrder>);
  @override
  _i13.Future<void> cancelFoodOrder(int? pk) => (super.noSuchMethod(
      Invocation.method(#cancelFoodOrder, [pk]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<_i7.FoodOrder> placeFoodOrder({int? eventPk, int? productPk}) =>
      (super.noSuchMethod(
              Invocation.method(#placeFoodOrder, [],
                  {#eventPk: eventPk, #productPk: productPk}),
              returnValue: Future<_i7.FoodOrder>.value(_FakeFoodOrder_6()))
          as _i13.Future<_i7.FoodOrder>);
  @override
  _i13.Future<_i7.FoodOrder> changeFoodOrder({int? eventPk, int? productPk}) =>
      (super.noSuchMethod(
              Invocation.method(#changeFoodOrder, [],
                  {#eventPk: eventPk, #productPk: productPk}),
              returnValue: Future<_i7.FoodOrder>.value(_FakeFoodOrder_6()))
          as _i13.Future<_i7.FoodOrder>);
  @override
  _i13.Future<_i3.ListResponse<_i16.Product>> getFoodEventProducts(int? pk,
          {int? limit, int? offset, String? search}) =>
      (super.noSuchMethod(
              Invocation.method(#getFoodEventProducts, [pk],
                  {#limit: limit, #offset: offset, #search: search}),
              returnValue: Future<_i3.ListResponse<_i16.Product>>.value(
                  _FakeListResponse_1<_i16.Product>()))
          as _i13.Future<_i3.ListResponse<_i16.Product>>);
  @override
  _i13.Future<_i8.PaymentUser> getPaymentUser() =>
      (super.noSuchMethod(Invocation.method(#getPaymentUser, []),
              returnValue: Future<_i8.PaymentUser>.value(_FakePaymentUser_7()))
          as _i13.Future<_i8.PaymentUser>);
  @override
  _i13.Future<_i5.Payable> getFoodOrderPayable({int? foodOrderPk}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getFoodOrderPayable, [], {#foodOrderPk: foodOrderPk}),
              returnValue: Future<_i5.Payable>.value(_FakePayable_4()))
          as _i13.Future<_i5.Payable>);
  @override
  _i13.Future<_i5.Payable> thaliaPayFoodOrder({int? foodOrderPk}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #thaliaPayFoodOrder, [], {#foodOrderPk: foodOrderPk}),
              returnValue: Future<_i5.Payable>.value(_FakePayable_4()))
          as _i13.Future<_i5.Payable>);
  @override
  _i13.Future<_i5.Payable> getEventRegistrationPayable({int? registrationPk}) =>
      (super.noSuchMethod(
              Invocation.method(#getEventRegistrationPayable, [],
                  {#registrationPk: registrationPk}),
              returnValue: Future<_i5.Payable>.value(_FakePayable_4()))
          as _i13.Future<_i5.Payable>);
  @override
  _i13.Future<_i5.Payable> thaliaPayRegistration({int? registrationPk}) =>
      (super.noSuchMethod(
              Invocation.method(#thaliaPayRegistration, [],
                  {#registrationPk: registrationPk}),
              returnValue: Future<_i5.Payable>.value(_FakePayable_4()))
          as _i13.Future<_i5.Payable>);
  @override
  _i13.Future<_i5.Payable> getSalesOrderPayable({String? salesOrderPk}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getSalesOrderPayable, [], {#salesOrderPk: salesOrderPk}),
              returnValue: Future<_i5.Payable>.value(_FakePayable_4()))
          as _i13.Future<_i5.Payable>);
  @override
  _i13.Future<_i5.Payable> thaliaPaySalesOrder({String? salesOrderPk}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #thaliaPaySalesOrder, [], {#salesOrderPk: salesOrderPk}),
              returnValue: Future<_i5.Payable>.value(_FakePayable_4()))
          as _i13.Future<_i5.Payable>);
  @override
  _i13.Future<_i9.Member> getMember({int? pk}) =>
      (super.noSuchMethod(Invocation.method(#getMember, [], {#pk: pk}),
              returnValue: Future<_i9.Member>.value(_FakeMember_8()))
          as _i13.Future<_i9.Member>);
  @override
  _i13.Future<_i3.ListResponse<_i9.ListMember>> getMembers(
          {String? search, int? limit, int? offset, String? ordering}) =>
      (super.noSuchMethod(
              Invocation.method(#getMembers, [], {
                #search: search,
                #limit: limit,
                #offset: offset,
                #ordering: ordering
              }),
              returnValue: Future<_i3.ListResponse<_i9.ListMember>>.value(
                  _FakeListResponse_1<_i9.ListMember>()))
          as _i13.Future<_i3.ListResponse<_i9.ListMember>>);
  @override
  _i13.Future<_i9.FullMember> getMe() =>
      (super.noSuchMethod(Invocation.method(#getMe, []),
              returnValue: Future<_i9.FullMember>.value(_FakeFullMember_9()))
          as _i13.Future<_i9.FullMember>);
  @override
  _i13.Future<void> updateAvatar(_i17.File? file) => (super.noSuchMethod(
      Invocation.method(#updateAvatar, [file]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<void> updateDescription(String? description) =>
      (super.noSuchMethod(Invocation.method(#updateDescription, [description]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<_i10.Album> getAlbum({String? slug}) =>
      (super.noSuchMethod(Invocation.method(#getAlbum, [], {#slug: slug}),
              returnValue: Future<_i10.Album>.value(_FakeAlbum_10()))
          as _i13.Future<_i10.Album>);
  @override
  _i13.Future<_i3.ListResponse<_i10.ListAlbum>> getAlbums(
          {String? search, int? limit, int? offset}) =>
      (super.noSuchMethod(
              Invocation.method(#getAlbums, [],
                  {#search: search, #limit: limit, #offset: offset}),
              returnValue: Future<_i3.ListResponse<_i10.ListAlbum>>.value(
                  _FakeListResponse_1<_i10.ListAlbum>()))
          as _i13.Future<_i3.ListResponse<_i10.ListAlbum>>);
  @override
  _i13.Future<_i3.ListResponse<_i18.Slide>> getSlides(
          {int? limit, int? offset}) =>
      (super.noSuchMethod(
          Invocation.method(#getSlides, [], {#limit: limit, #offset: offset}),
          returnValue: Future<_i3.ListResponse<_i18.Slide>>.value(
              _FakeListResponse_1<_i18.Slide>())) as _i13
          .Future<_i3.ListResponse<_i18.Slide>>);
  @override
  _i13.Future<_i3.ListResponse<_i19.FrontpageArticle>> getFrontpageArticles(
          {int? limit, int? offset}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getFrontpageArticles, [], {#limit: limit, #offset: offset}),
          returnValue: Future<_i3.ListResponse<_i19.FrontpageArticle>>.value(
              _FakeListResponse_1<_i19.FrontpageArticle>())) as _i13
          .Future<_i3.ListResponse<_i19.FrontpageArticle>>);
  @override
  _i13.Future<_i11.Device> getDevice({int? id}) =>
      (super.noSuchMethod(Invocation.method(#getDevice, [], {#id: id}),
              returnValue: Future<_i11.Device>.value(_FakeDevice_11()))
          as _i13.Future<_i11.Device>);
  @override
  _i13.Future<_i11.Device> putDevice({int? id, _i11.Device? device}) =>
      (super.noSuchMethod(
              Invocation.method(#putDevice, [], {#id: id, #device: device}),
              returnValue: Future<_i11.Device>.value(_FakeDevice_11()))
          as _i13.Future<_i11.Device>);
  @override
  _i13.Future<_i11.Device> registerDevice(
          {String? token, String? type, bool? active}) =>
      (super.noSuchMethod(
              Invocation.method(#registerDevice, [],
                  {#token: token, #type: type, #active: active}),
              returnValue: Future<_i11.Device>.value(_FakeDevice_11()))
          as _i13.Future<_i11.Device>);
  @override
  _i13.Future<_i3.ListResponse<_i20.PushNotificationCategory>>
      getCategories() => (super.noSuchMethod(
              Invocation.method(#getCategories, []),
              returnValue:
                  Future<_i3.ListResponse<_i20.PushNotificationCategory>>.value(
                      _FakeListResponse_1<_i20.PushNotificationCategory>()))
          as _i13.Future<_i3.ListResponse<_i20.PushNotificationCategory>>);
}
