---
name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  FLUTTER_VERSION: 3.22.2

jobs:
  integration-ios:
    name: Integration Testing - iOS
    runs-on: macos-13
    steps:
      - name: "List all simulators"
        run: "xcrun xctrace list devices"

      - name: "Start Simulator"
        env:
          DEVICE: ${{ vars.IOS_SIMULATOR }}
        run: |
          UDID=$(xcrun xctrace list devices | grep "^$DEVICE (" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: log
        run: |
          ls /Users/runner/hostedtoolcache/flutter/stable-3.22.2-x64
          which flutter
          cat /Users/runner/hostedtoolcache/flutter/stable-3.22.2-x64/packages/flutter/lib/src/rendering/layer.dart
      - name: Run integration tests
        run: |
          flutter drive -v --driver=test_driver/integration_test.dart --target=integration_test/main.dart 
